sonar-project.properties
sonar.projectKey=fd6baf188313b6a6549e833e8a70ddbca51bb24f
sonar.organization=anand152002
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8